### ISSUE TITLE
Debug message causes Fatal error

### ISSUE THREAD

**Issue by defensivedepth** [logstash-plugins/logstash-filter-http#12]
I have a very simple pipeline using the following http filter, but I continue to get errors (see here: https://gist.github.com/defensivedepth/7b8d22aeec6dedac6438d8adeaed4b1d 1)

I have tried different sites, different settings, but always come back to this error. Logstash 6.6.1

Appears to be a bug -  https://discuss.elastic.co/t/http-filter-undefined-local-variable-or-method-parameters-sprintfed/169905? 

-----------
input {
file {
path => "/input*.json"
codec => json
}

}

filter {
http {
url => "https://site.com/%{identifier}"
}

}

output {
stdout {}
}

**Comment by michaelhyatt** [comment]
Same with Logstash 6.7.0

**Comment by ttimasdf** [comment]
the `parameter_sprintfed` is not defined elsewhere
https://github.com/logstash-plugins/logstash-filter-http/blob/9d9a837f85f1e8c6ac759fe7202427ed2351069b/lib/logstash/filters/http.rb#L54
